---
name: 'Python Semantic Release'

description: 'Automatic Semantic Versioning for Python projects'

inputs:
  additional_options:
    description: 'Additional options for the publish command. Example: --noop'
    required: false
  directory:
    description: 'Sub-directory to cd into before running semantic-release'
    default: '.'
    required: false
  github_token:
    description: 'GitHub token used to push release notes and new commits/tags'
    required: true
  pypi_token:
    description: 'PyPI API token'
    required: false
  repository_username:
    description: 'Username with project access to push to Artifact Repository'
    required: false
  repository_password:
    description: 'Password or token to the account specified in repository_username'
    required: false
  git_committer_name:
    description: 'The human name for the “committer” field'
    required: false
  git_committer_email:
    description: 'The email address for the “committer” field'
    required: false
  ssh_public_signing_key:
    description: 'The ssh public key used to sign commits'
    required: false
  ssh_private_signing_key:
    description: 'The ssh private key used to sign commits'
    required: false
outputs:
  current_release_version:
    description: 'Current release version.'
  current_release_major_version:
    description: Current release major version.'
  current_release_minor_version:
    description: Current release minor version.'
  current_release_patch_version:
    description: Current release patch version.'
  new_release_published:
    description: '"true" if a new release was published, else "false".'
  new_release_version:
    description: 'Newly created release version.'
  new_release_major_version:
    description: 'Newly created release major version.'
  new_release_minor_version:
    description: 'Newly created release minor version.'
  new_release_patch_version:
    description: 'Newly created release patch version.'

runs:
  using: 'docker'
  image: 'Dockerfile'
